/***************************************************************************
* Copyright (C) 2023 ETH Zurich
* Core AI & Digital Biomarker, Acoustic and Inflammatory Biomarkers (ADAMMA)
* Centre for Digital Health Interventions (c4dhi.org)
* 
* Authors: Patrick Langer
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*         http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
***************************************************************************/


#include <jni.h>
#include "JBindWrapper/JBindWrapper.hpp"
extern "C" 
{
    JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *pjvm, void *reserved)
    {
        printf("ONLOAD %lu\n", (intptr_t)&jbind11::getClassLoader());
        std::cout << std::flush;
        jbind11::getClassLoader().onLoad(pjvm);
        printf("Classloader %lu\n", (intptr_t)&jbind11::getClassLoader());
                std::cout << std::flush;

        // This will call the corresponding functions
        // generated by all included JBIND_PACKAGE(...) declarations.
        jbind11::getPackageManager().initializePackages();



        return JNI_VERSION_1_6;
    }
}