#pragma once

#include <jni.h>
#include "JavaPackage/JavaPackageRegistrar.hpp"
#include "JavaClass/JavaClass.hpp"
#include "JavaHandle/JavaHandle.hpp"
#include "cast.hpp"

#include "jbind11_macros.hpp"
#include "JBindWrapper/JBindWrapper.hpp"
#include "JBindWrapper/JBindWrapperGenerator.hpp"
#include "JavaPackage/JavaPackageManager.hpp"

#include "attr.hpp"

extern "C" 
{
    JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *pjvm, void *reserved)
    {
        printf("ONLOAD\n");
        jbind11::ClassLoader::onLoad(pjvm);

        // This will call the corresponding functions
        // generated by all included JBIND_PACKAGE(...) declarations.
        jbind11::JavaPackageManager::initializePackages();


        JavaPackage* package = jbind11::JavaPackageManager::getPackage("JavaCLAIDDataTypes");

        if(package == nullptr)
        {
            JBIND_THROW("Error package not found");
        }

        return JNI_VERSION_1_6;
    }
}