
#include <jni.h>
#include "JBindWrapper/JBindWrapper.hpp"
extern "C" 
{
    JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *pjvm, void *reserved)
    {
        printf("ONLOAD %lu\n", (intptr_t)&jbind11::getClassLoader());
        std::cout << std::flush;
        jbind11::getClassLoader().onLoad(pjvm);
        printf("Classloader %lu\n", (intptr_t)&jbind11::getClassLoader());
                std::cout << std::flush;

        // This will call the corresponding functions
        // generated by all included JBIND_PACKAGE(...) declarations.
        jbind11::getPackageManager().initializePackages();


        jbind11::JavaPackage* package = jbind11::getPackageManager().getPackage("JavaCLAIDDataTypes");

        if(package == nullptr)
        {
            JBIND_THROW("Error package not found");
        }

        return JNI_VERSION_1_6;
    }
}